"""Ports exposed by memory_core."""

from memory_core.ports.adapters import (
    AdapterCapabilities,
    GraphCandidate,
    GraphSearchResult,
    MemoryAdapterPort,
    PortDiagnostic,
    PortStatus,
    VectorCandidate,
    VectorSearchResult,
)
from memory_core.ports.auth import AuthPort, MemoryPrincipal, MemoryScope, ReadScope
from memory_core.ports.auto_memory import (
    FactExtractionPort,
    MemoryCandidate,
    MemoryClassifierPort,
    SourceProvenance,
)
from memory_core.ports.capabilities import (
    CapabilityDescriptor,
    CapabilityDiagnostic,
    CapabilityMode,
    CapabilityRecallCandidate,
    CapabilityRecallQuery,
    CapabilityRecallResult,
    CapabilityStatus,
    ConsistencyMode,
    DocumentMemoryPort,
    DocumentMemoryWrite,
    EngineHealthPort,
    EngineHealthSnapshot,
    FactProjectionPort,
    FactProjectionWrite,
    MemoryCapability,
    MemoryScopeFilter,
    ProjectionForgetPort,
    ProjectionForgetRequest,
    ProjectionForgetResult,
    ProjectionFreshness,
    ProjectionWriteResult,
    RagRecallPort,
    SessionMemoryPort,
    TemporalFactGraphPort,
    VectorRecallPort,
)
from memory_core.ports.clock import ClockPort
from memory_core.ports.ids import IdGeneratorPort

__all__ = [
    "AdapterCapabilities",
    "AuthPort",
    "CapabilityDescriptor",
    "CapabilityDiagnostic",
    "CapabilityMode",
    "CapabilityRecallCandidate",
    "CapabilityRecallQuery",
    "CapabilityRecallResult",
    "CapabilityStatus",
    "ClockPort",
    "ConsistencyMode",
    "DocumentMemoryPort",
    "DocumentMemoryWrite",
    "EngineHealthPort",
    "EngineHealthSnapshot",
    "FactExtractionPort",
    "FactProjectionPort",
    "FactProjectionWrite",
    "GraphCandidate",
    "GraphSearchResult",
    "IdGeneratorPort",
    "MemoryAdapterPort",
    "MemoryCandidate",
    "MemoryCapability",
    "MemoryClassifierPort",
    "MemoryPrincipal",
    "MemoryScope",
    "MemoryScopeFilter",
    "PortDiagnostic",
    "PortStatus",
    "ProjectionForgetPort",
    "ProjectionForgetRequest",
    "ProjectionForgetResult",
    "ProjectionFreshness",
    "ProjectionWriteResult",
    "RagRecallPort",
    "ReadScope",
    "SessionMemoryPort",
    "SourceProvenance",
    "TemporalFactGraphPort",
    "VectorCandidate",
    "VectorRecallPort",
    "VectorSearchResult",
]
