"""Ports exposed by memo_stack_core."""

from memo_stack_core.ports.adapters import (
    AdapterCapabilities,
    GraphCandidate,
    GraphSearchResult,
    MemoryAdapterPort,
    PortDiagnostic,
    PortStatus,
    VectorCandidate,
    VectorSearchResult,
)
from memo_stack_core.ports.auth import AuthPort, MemoryUser, MemoryWriteScope, ReadScope
from memo_stack_core.ports.auto_memory import (
    ALLOWED_TTL_POLICIES,
    FactExtractionPort,
    MemoryCandidate,
    MemoryClassifierPort,
    MemoryExtractorPort,
    SourceProvenance,
)
from memo_stack_core.ports.capabilities import (
    CapabilityDescriptor,
    CapabilityDiagnostic,
    CapabilityMode,
    CapabilityRecallCandidate,
    CapabilityRecallQuery,
    CapabilityRecallResult,
    CapabilityStatus,
    ConsistencyMode,
    DocumentMemoryPort,
    DocumentMemoryWrite,
    EngineHealthPort,
    EngineHealthSnapshot,
    FactProjectionPort,
    FactProjectionWrite,
    MemoryCapability,
    MemoryScopeFilter,
    ProjectionForgetPort,
    ProjectionForgetRequest,
    ProjectionForgetResult,
    ProjectionFreshness,
    ProjectionWriteResult,
    RagRecallPort,
    SessionMemoryPort,
    TemporalFactGraphPort,
    VectorRecallPort,
)
from memo_stack_core.ports.clock import ClockPort
from memo_stack_core.ports.extraction import (
    AssetExtractionRepositoryPort,
    ContentExtractionPort,
    ExtractedElement,
    ExtractionArtifactCandidate,
    ExtractionLimits,
    ExtractionRequest,
    ExtractionResult,
    FileTypeDetectionRequest,
    FileTypeDetectionResult,
    FileTypeDetectorPort,
)
from memo_stack_core.ports.ids import IdGeneratorPort
from memo_stack_core.ports.transcription import (
    SpeechTranscriptionPort,
    SpeechTranscriptionRequest,
    SpeechTranscriptionResult,
    SpeechTranscriptSegment,
)
from memo_stack_core.ports.usage import UsageRepositoryPort

__all__ = [
    "AdapterCapabilities",
    "ALLOWED_TTL_POLICIES",
    "AuthPort",
    "AssetExtractionRepositoryPort",
    "CapabilityDescriptor",
    "CapabilityDiagnostic",
    "CapabilityMode",
    "CapabilityRecallCandidate",
    "CapabilityRecallQuery",
    "CapabilityRecallResult",
    "CapabilityStatus",
    "ClockPort",
    "ConsistencyMode",
    "ContentExtractionPort",
    "DocumentMemoryPort",
    "DocumentMemoryWrite",
    "EngineHealthPort",
    "EngineHealthSnapshot",
    "ExtractedElement",
    "ExtractionArtifactCandidate",
    "ExtractionLimits",
    "ExtractionRequest",
    "ExtractionResult",
    "FactExtractionPort",
    "FactProjectionPort",
    "FactProjectionWrite",
    "FileTypeDetectionRequest",
    "FileTypeDetectionResult",
    "FileTypeDetectorPort",
    "GraphCandidate",
    "GraphSearchResult",
    "IdGeneratorPort",
    "MemoryAdapterPort",
    "MemoryCandidate",
    "MemoryCapability",
    "MemoryClassifierPort",
    "MemoryExtractorPort",
    "MemoryUser",
    "MemoryWriteScope",
    "MemoryScopeFilter",
    "PortDiagnostic",
    "PortStatus",
    "ProjectionForgetPort",
    "ProjectionForgetRequest",
    "ProjectionForgetResult",
    "ProjectionFreshness",
    "ProjectionWriteResult",
    "RagRecallPort",
    "ReadScope",
    "SessionMemoryPort",
    "SpeechTranscriptSegment",
    "SpeechTranscriptionPort",
    "SpeechTranscriptionRequest",
    "SpeechTranscriptionResult",
    "SourceProvenance",
    "TemporalFactGraphPort",
    "UsageRepositoryPort",
    "VectorCandidate",
    "VectorRecallPort",
    "VectorSearchResult",
]
