"""Reason-specific scoring policy for context ranking."""

from __future__ import annotations

KEYWORD_EXPANSION_SCORE_CAPS = {
    "adoption_current_goal_bridge": 0.96,
    "adoption_current_milestone_bridge": 0.98,
    "age_birthday_bridge": 0.96,
    "activity_aggregation_bridge": 0.96,
    "activity_visual_selfcare_bridge": 0.96,
    "audio_transcript_evidence_bridge": 0.96,
    "artifact_inventory_bridge": 0.96,
    "avoidance_constraint_bridge": 0.94,
    "art_style_bridge": 0.96,
    "attribute_calm_resourcefulness_bridge": 0.96,
    "beach_count_activity_bridge": 0.96,
    "animal_affinity_pet_store_bridge": 0.96,
    "animal_care_instruction_bridge": 0.96,
    "animal_career_inference_bridge": 0.96,
    "animal_diet_evidence_bridge": 0.96,
    "animal_habitat_setup_bridge": 0.96,
    "attribute_family_support_bridge": 0.96,
    "attribute_rescue_purpose_bridge": 0.96,
    "attribute_service_helpfulness_bridge": 0.96,
    "attribute_trait_inventory_bridge": 0.96,
    "ally_support_bridge": 0.96,
    "allergy_condition_inference_bridge": 0.96,
    "allergy_inventory_bridge": 0.96,
    "birdwatching_city_schedule_bridge": 0.96,
    "book_suggestion_bridge": 0.96,
    "birthplace_origin_bridge": 0.96,
    "business_commonality_bridge": 0.96,
    "business_networking_event_bridge": 0.96,
    "business_opening_timeline_bridge": 0.96,
    "business_promotion_event_bridge": 0.96,
    "business_start_reason_bridge": 0.96,
    "business_store_promotion_event_bridge": 0.96,
    "store_promotion_inventory_bridge": 0.96,
    "career_intent_bridge": 0.96,
    "charity_brand_sponsorship_bridge": 0.96,
    "charity_tournament_count_bridge": 0.96,
    "children_books_inference_bridge": 0.96,
    "children_count_event_bridge": 0.96,
    "children_preference_bridge": 0.96,
    "classical_music_preference_bridge": 0.96,
    "commonality_interest_bridge": 0.96,
    "community_membership_bridge": 0.95,
    "community_membership_support_bridge": 0.95,
    "conversation_transcript_evidence_bridge": 0.95,
    "cause_education_infrastructure_inventory_bridge": 0.98,
    "cause_veterans_inventory_bridge": 0.98,
    "current_residence_bridge": 0.96,
    "current_recommendation_bridge": 0.95,
    "current_state_temporal_bridge": 0.95,
    "current_occupation_bridge": 0.96,
    "degree_policy_inference_bridge": 0.96,
    "decomposition_action_role": 0.95,
    "decomposition_absence_contrast": 0.94,
    "decomposition_activity_participation": 0.96,
    "decomposition_ally_support_evidence": 0.96,
    "decomposition_artifact_evidence": 0.96,
    "decomposition_commonality": 0.95,
    "decomposition_community_membership_evidence": 0.95,
    "decomposition_conversation_counterparty": 0.96,
    "decomposition_conversation_recency": 0.96,
    "decomposition_conversation_topic": 0.96,
    "decomposition_counterfactual_evidence": 0.95,
    "decomposition_activity_duration": 0.95,
    "decomposition_deadline_commitment": 0.96,
    "decomposition_emotion_cause": 0.95,
    "decomposition_evidence_reason": 0.95,
    "decomposition_event_sequence": 0.95,
    "decomposition_followup_task": 0.96,
    "decomposition_gotcha_failure": 0.96,
    "decomposition_inference_support": 0.95,
    "decomposition_inventory_list": 0.96,
    "decomposition_knowledge_update_current": 0.96,
    "decomposition_knowledge_update_previous": 0.95,
    "decomposition_lgbtq_pride_event": 0.96,
    "decomposition_lgbtq_school_speech_event": 0.96,
    "decomposition_lgbtq_support_group_event": 0.96,
    "decomposition_frequency_recurrence": 0.95,
    "decomposition_quantity_count": 0.95,
    "decomposition_recommendation_source": 0.96,
    "decomposition_relocation_context": 0.96,
    "decomposition_relocation_destination": 0.96,
    "decomposition_source_evidence": 0.95,
    "decomposition_state_transition": 0.96,
    "decomposition_support_role_fit": 0.96,
    "decomposition_temporal_answer": 0.95,
    "deadline_commitment_bridge": 0.96,
    "education_career_field_bridge": 0.96,
    "entity_relation_inventory_bridge": 0.96,
    "event_summary_bridge": 0.96,
    "exercise_activity_inventory_bridge": 0.96,
    "endorsement_gear_brand_bridge": 0.96,
    "event_participation_bridge": 0.96,
    "family_origin_bridge": 0.96,
    "food_preference_bridge": 0.96,
    "food_recipe_recommendation_bridge": 0.96,
    "followup_task_bridge": 0.96,
    "friend_place_inventory_bridge": 0.98,
    "friend_place_shelter_inventory_bridge": 0.98,
    "friend_place_gym_inventory_bridge": 0.98,
    "friend_place_church_inventory_bridge": 0.98,
    "generic_behavior_inference_bridge": 0.95,
    "gotcha_failure_bridge": 0.96,
    "gaming_medium_bridge": 0.96,
    "hobby_interest_bridge": 0.96,
    "identity_bridge": 0.96,
    "instrument_play_bridge": 0.96,
    "item_purchase_bridge": 0.96,
    "hike_count_activity_bridge": 0.96,
    "hiking_trail_count_bridge": 0.96,
    "letter_count_bridge": 0.96,
    "lgbtq_pride_event_bridge": 0.96,
    "lgbtq_school_event_bridge": 0.96,
    "lgbtq_support_group_event_bridge": 0.96,
    "motivation_reason_bridge": 0.95,
    "military_service_willingness_bridge": 0.98,
    "music_artist_answer_bridge": 0.96,
    "music_artist_band_bridge": 0.96,
    "national_park_inference_bridge": 0.98,
    "negative_experience_support_bridge": 0.96,
    "negative_preference_bridge": 0.94,
    "ordinal_answer_bridge": 0.95,
    "organization_summary_bridge": 0.96,
    "pet_count_bridge": 0.96,
    "pet_inventory_bridge": 0.96,
    "person_summary_bridge": 0.96,
    "possession_gift_object_bridge": 0.96,
    "quantity_enumeration_bridge": 0.94,
    "recommendation_source_bridge": 0.95,
    "relationship_status_bridge": 0.96,
    "relationship_duration_bridge": 0.96,
    "relationship_origin_bridge": 0.96,
    "religious_inference_bridge": 0.96,
    "running_reason_bridge": 0.96,
    "running_reason_question_bridge": 0.98,
    "shoe_usage_bridge": 0.96,
    "speaker_turn_bridge": 0.95,
    "shelter_comfort_reason_bridge": 0.96,
    "source_evidence_bridge": 0.95,
    "state_residence_inference_bridge": 0.96,
    "state_transition_bridge": 0.96,
    "stale_state_temporal_bridge": 0.94,
    "study_time_management_bridge": 0.96,
    "travel_country_inventory_bridge": 0.98,
    "support_career_motivation_bridge": 0.96,
    "support_counterfactual_bridge": 0.94,
    "support_network_bridge": 0.96,
    "support_origin_bridge": 0.94,
    "support_role_fit_bridge": 0.96,
    "temporal_event_detail_bridge": 0.96,
    "outdoor_preference_bridge": 0.94,
    "outdoor_nature_memory_bridge": 0.94,
    "patriotic_service_inference_bridge": 0.98,
    "personality_trait_bridge": 0.94,
    "personality_authenticity_bridge": 0.94,
    "personality_drive_bridge": 0.98,
    "personality_thoughtfulness_bridge": 0.94,
    "painting_inventory_bridge": 0.96,
    "political_inference_bridge": 0.96,
    "post_event_emotion_bridge": 0.95,
    "post_event_activity_timing_bridge": 0.98,
    "post_athletic_career_bridge": 0.96,
    "pottery_type_bridge": 0.96,
    "project_summary_bridge": 0.96,
    "public_office_service_bridge": 0.98,
    "relocation_destination_bridge": 0.96,
    "relocation_origin_bridge": 0.96,
    "relocation_willingness_inference_bridge": 0.98,
    "adverse_trip_bridge": 0.94,
    "trip_destination_bridge": 0.96,
    "camping_detail_bridge": 0.95,
    "family_hike_detail_bridge": 0.96,
    "family_hike_activity_bridge": 0.96,
    "book_reading_list_bridge": 0.96,
    "shared_painted_subject_bridge": 0.96,
    "screenplay_count_bridge": 0.96,
    "symbol_importance_bridge": 0.96,
    "transgender_conference_event_bridge": 0.96,
    "transgender_poetry_event_bridge": 0.96,
    "transgender_youth_center_event_bridge": 0.96,
    "tournament_count_bridge": 0.96,
    "video_transcript_evidence_bridge": 0.96,
    "visual_text_evidence_bridge": 0.96,
    "volunteer_career_inference_bridge": 0.96,
    "wellness_activity_effect_bridge": 0.96,
    "yoga_delay_gaming_bridge": 0.96,
}

KEYWORD_EXPANSION_REASON_BOOSTS = {
    "adoption_current_goal_bridge": 0.024,
    "adoption_current_milestone_bridge": 0.034,
    "adverse_trip_bridge": 0.012,
    "age_birthday_bridge": 0.06,
    "audio_transcript_evidence_bridge": 0.032,
    "artifact_inventory_bridge": 0.028,
    "allergy_condition_inference_bridge": 0.04,
    "allergy_inventory_bridge": 0.028,
    "animal_affinity_pet_store_bridge": 0.052,
    "animal_care_instruction_bridge": 0.052,
    "animal_career_inference_bridge": 0.064,
    "animal_diet_evidence_bridge": 0.052,
    "animal_habitat_setup_bridge": 0.052,
    "art_style_bridge": 0.022,
    "attribute_description_bridge": 0.018,
    "attribute_calm_resourcefulness_bridge": 0.04,
    "attribute_family_support_bridge": 0.04,
    "attribute_rescue_purpose_bridge": 0.04,
    "attribute_service_helpfulness_bridge": 0.04,
    "attribute_trait_inventory_bridge": 0.04,
    "activity_aggregation_bridge": 0.02,
    "activity_visual_selfcare_bridge": 0.024,
    "ally_support_bridge": 0.028,
    "avoidance_constraint_bridge": 0.022,
    "beach_count_activity_bridge": 0.028,
    "beach_or_mountains_inference_bridge": 0.018,
    "birthplace_origin_bridge": 0.052,
    "birdwatching_city_schedule_bridge": 0.046,
    "book_reading_list_bridge": 0.028,
    "book_suggestion_bridge": 0.025,
    "business_commonality_bridge": 0.055,
    "business_networking_event_bridge": 0.044,
    "business_opening_timeline_bridge": 0.042,
    "business_promotion_event_bridge": 0.038,
    "business_start_reason_bridge": 0.032,
    "business_store_promotion_event_bridge": 0.038,
    "store_promotion_inventory_bridge": 0.04,
    "camping_detail_bridge": 0.018,
    "career_intent_bridge": 0.03,
    "cause_education_infrastructure_inventory_bridge": 0.04,
    "cause_veterans_inventory_bridge": 0.04,
    "charity_brand_sponsorship_bridge": 0.032,
    "charity_tournament_count_bridge": 0.03,
    "children_books_inference_bridge": 0.024,
    "children_count_event_bridge": 0.024,
    "children_count_sibling_bridge": 0.016,
    "children_preference_bridge": 0.026,
    "classical_music_preference_bridge": 0.024,
    "commonality_interest_bridge": 0.024,
    "community_membership_bridge": 0.02,
    "community_membership_support_bridge": 0.024,
    "decomposition_community_membership_evidence": 0.024,
    "conversation_transcript_evidence_bridge": 0.024,
    "current_occupation_bridge": 0.052,
    "current_residence_bridge": 0.052,
    "current_recommendation_bridge": 0.024,
    "current_state_temporal_bridge": 0.026,
    "console_game_cover_bridge": 0.018,
    "counseling_workshop_bridge": 0.018,
    "degree_policy_inference_bridge": 0.052,
    "education_career_field_bridge": 0.022,
    "exercise_activity_inventory_bridge": 0.06,
    "endorsement_gear_brand_bridge": 0.032,
    "decomposition_activity_participation": 0.02,
    "decomposition_action_role": 0.018,
    "decomposition_absence_contrast": 0.022,
    "decomposition_artifact_evidence": 0.026,
    "decomposition_attribute_aggregation": 0.018,
    "decomposition_commonality": 0.02,
    "decomposition_conversation_counterparty": 0.028,
    "decomposition_conversation_recency": 0.03,
    "decomposition_conversation_topic": 0.026,
    "decomposition_counterfactual_evidence": 0.016,
    "decomposition_activity_duration": 0.022,
    "decomposition_ally_support_evidence": 0.032,
    "decomposition_current_preference_or_goal": 0.018,
    "decomposition_deadline_commitment": 0.03,
    "decomposition_emotion_cause": 0.024,
    "decomposition_evidence_reason": 0.024,
    "decomposition_event_sequence": 0.018,
    "decomposition_followup_task": 0.032,
    "decomposition_gotcha_failure": 0.034,
    "decomposition_inference_support": 0.02,
    "decomposition_inventory_list": 0.024,
    "decomposition_identity_attribute": 0.02,
    "decomposition_knowledge_update_current": 0.018,
    "decomposition_knowledge_update_previous": 0.018,
    "decomposition_lgbtq_pride_event": 0.024,
    "decomposition_lgbtq_school_speech_event": 0.024,
    "decomposition_lgbtq_support_group_event": 0.024,
    "decomposition_frequency_recurrence": 0.02,
    "decomposition_quantity_count": 0.02,
    "decomposition_recommendation_source": 0.026,
    "decomposition_relocation_context": 0.026,
    "decomposition_relocation_destination": 0.026,
    "decomposition_source_evidence": 0.026,
    "decomposition_state_transition": 0.034,
    "decomposition_support_role_fit": 0.032,
    "decomposition_temporal_answer": 0.024,
    "decomposition_relationship_status": 0.02,
    "deadline_commitment_bridge": 0.05,
    "entity_relation_inventory_bridge": 0.024,
    "event_summary_bridge": 0.026,
    "event_participation_bridge": 0.018,
    "family_origin_bridge": 0.024,
    "followup_task_bridge": 0.044,
    "friend_place_inventory_bridge": 0.04,
    "friend_place_shelter_inventory_bridge": 0.04,
    "friend_place_gym_inventory_bridge": 0.04,
    "friend_place_church_inventory_bridge": 0.04,
    "gotcha_failure_bridge": 0.046,
    "family_activity_bridge": 0.024,
    "family_hike_detail_bridge": 0.026,
    "family_hike_activity_bridge": 0.024,
    "family_museum_activity_bridge": 0.022,
    "family_motivation_context_bridge": 0.02,
    "family_painting_activity_bridge": 0.02,
    "family_swimming_activity_bridge": 0.02,
    "event_participation_help_bridge": 0.02,
    "food_preference_bridge": 0.026,
    "food_recipe_recommendation_bridge": 0.044,
    "friends_team_inference_bridge": 0.018,
    "generic_behavior_inference_bridge": 0.024,
    "gaming_medium_bridge": 0.026,
    "hike_count_activity_bridge": 0.022,
    "hiking_trail_count_bridge": 0.026,
    "hobby_interest_bridge": 0.026,
    "identity_bridge": 0.022,
    "instrument_play_bridge": 0.028,
    "item_purchase_bridge": 0.022,
    "letter_count_bridge": 0.026,
    "lgbtq_community_participation_bridge": 0.02,
    "lgbtq_pride_event_bridge": 0.02,
    "lgbtq_school_event_bridge": 0.02,
    "lgbtq_support_group_event_bridge": 0.02,
    "meteor_shower_feeling_bridge": 0.018,
    "military_service_willingness_bridge": 0.08,
    "music_artist_answer_bridge": 0.026,
    "motivation_reason_bridge": 0.02,
    "music_artist_band_bridge": 0.024,
    "national_park_inference_bridge": 0.052,
    "negative_experience_support_bridge": 0.024,
    "negative_preference_bridge": 0.022,
    "outdoor_nature_memory_bridge": 0.018,
    "organization_summary_bridge": 0.024,
    "painting_inventory_bridge": 0.028,
    "personality_authenticity_bridge": 0.014,
    "personality_drive_bridge": 0.08,
    "personality_thoughtfulness_bridge": 0.014,
    "personality_trait_bridge": 0.012,
    "person_summary_bridge": 0.024,
    "pet_allergy_discomfort_bridge": 0.018,
    "ordinal_answer_bridge": 0.022,
    "patriotic_service_inference_bridge": 0.08,
    "pet_count_bridge": 0.03,
    "pet_inventory_bridge": 0.028,
    "possession_gift_object_bridge": 0.026,
    "political_inference_bridge": 0.022,
    "post_event_emotion_bridge": 0.022,
    "post_event_activity_timing_bridge": 0.052,
    "post_athletic_career_bridge": 0.042,
    "pottery_color_reason_bridge": 0.018,
    "pottery_type_bridge": 0.024,
    "project_summary_bridge": 0.024,
    "public_office_service_bridge": 0.08,
    "quantity_enumeration_bridge": 0.018,
    "relationship_status_bridge": 0.022,
    "relationship_duration_bridge": 0.022,
    "relationship_origin_bridge": 0.022,
    "religious_inference_bridge": 0.04,
    "relocation_destination_bridge": 0.022,
    "relocation_origin_bridge": 0.022,
    "relocation_willingness_inference_bridge": 0.08,
    "running_reason_bridge": 0.04,
    "running_reason_question_bridge": 0.06,
    "shoe_usage_bridge": 0.018,
    "screenplay_count_bridge": 0.03,
    "shared_painted_subject_bridge": 0.024,
    "source_evidence_bridge": 0.026,
    "speaker_turn_bridge": 0.05,
    "shelter_comfort_reason_bridge": 0.032,
    "state_residence_inference_bridge": 0.026,
    "state_transition_bridge": 0.04,
    "stale_state_temporal_bridge": 0.022,
    "study_time_management_bridge": 0.04,
    "travel_country_inventory_bridge": 0.04,
    "support_career_motivation_bridge": 0.022,
    "support_network_bridge": 0.034,
    "support_origin_bridge": 0.01,
    "support_role_fit_bridge": 0.038,
    "symbol_importance_bridge": 0.024,
    "temporal_event_detail_bridge": 0.032,
    "transgender_poetry_event_bridge": 0.02,
    "transgender_conference_event_bridge": 0.022,
    "transgender_youth_center_event_bridge": 0.022,
    "tournament_count_bridge": 0.03,
    "video_transcript_evidence_bridge": 0.032,
    "visual_text_evidence_bridge": 0.034,
    "volunteer_career_inference_bridge": 0.052,
    "wellness_activity_effect_bridge": 0.052,
    "yoga_delay_gaming_bridge": 0.032,
}

QUERY_REASON_PRIORITY = {
    "relationship_duration_bridge": 5,
    "relationship_origin_bridge": 5,
    "activity_aggregation_bridge": 4,
    "activity_visual_selfcare_bridge": 4,
    "adoption_current_goal_bridge": 4,
    "adoption_current_milestone_bridge": 4,
    "age_birthday_bridge": 4,
    "audio_transcript_evidence_bridge": 6,
    "artifact_inventory_bridge": 4,
    "birthplace_origin_bridge": 4,
    "animal_affinity_pet_store_bridge": 4,
    "animal_care_instruction_bridge": 4,
    "animal_career_inference_bridge": 4,
    "animal_diet_evidence_bridge": 4,
    "animal_habitat_setup_bridge": 4,
    "birdwatching_city_schedule_bridge": 4,
    "book_reading_list_bridge": 4,
    "book_suggestion_bridge": 4,
    "beach_count_activity_bridge": 4,
    "business_commonality_bridge": 4,
    "business_networking_event_bridge": 6,
    "business_opening_timeline_bridge": 5,
    "business_promotion_event_bridge": 5,
    "business_start_reason_bridge": 4,
    "business_store_promotion_event_bridge": 5,
    "store_promotion_inventory_bridge": 5,
    "camping_detail_bridge": 4,
    "career_intent_bridge": 4,
    "charity_brand_sponsorship_bridge": 4,
    "charity_tournament_count_bridge": 4,
    "attribute_calm_resourcefulness_bridge": 4,
    "attribute_family_support_bridge": 4,
    "attribute_rescue_purpose_bridge": 4,
    "attribute_service_helpfulness_bridge": 4,
    "attribute_trait_inventory_bridge": 4,
    "ally_support_bridge": 4,
    "allergy_condition_inference_bridge": 4,
    "allergy_inventory_bridge": 4,
    "career_path_bridge": 4,
    "item_purchase_bridge": 4,
    "painting_inventory_bridge": 4,
    "shoe_usage_bridge": 4,
    "family_activity_bridge": 4,
    "family_hike_detail_bridge": 4,
    "family_hike_activity_bridge": 4,
    "family_museum_activity_bridge": 4,
    "family_motivation_context_bridge": 3,
    "family_painting_activity_bridge": 4,
    "family_swimming_activity_bridge": 4,
    "hike_count_activity_bridge": 4,
    "hiking_trail_count_bridge": 4,
    "letter_count_bridge": 4,
    "children_books_inference_bridge": 4,
    "children_count_event_bridge": 4,
    "children_preference_bridge": 4,
    "shared_painted_subject_bridge": 4,
    "classical_music_preference_bridge": 4,
    "commonality_interest_bridge": 4,
    "current_occupation_bridge": 4,
    "current_residence_bridge": 4,
    "current_recommendation_bridge": 3,
    "current_state_temporal_bridge": 3,
    "community_membership_bridge": 4,
    "community_membership_support_bridge": 4,
    "cause_education_infrastructure_inventory_bridge": 5,
    "cause_veterans_inventory_bridge": 5,
    "deadline_commitment_bridge": 4,
    "decomposition_evidence_reason": 4,
    "decomposition_emotion_cause": 4,
    "decomposition_gotcha_failure": 4,
    "decomposition_state_transition": 4,
    "degree_policy_inference_bridge": 4,
    "endorsement_gear_brand_bridge": 4,
    "education_career_field_bridge": 4,
    "entity_relation_inventory_bridge": 4,
    "event_summary_bridge": 4,
    "exercise_activity_inventory_bridge": 4,
    "friend_place_inventory_bridge": 5,
    "friend_place_shelter_inventory_bridge": 5,
    "friend_place_gym_inventory_bridge": 5,
    "friend_place_church_inventory_bridge": 5,
    "followup_task_bridge": 4,
    "gotcha_failure_bridge": 4,
    "state_transition_bridge": 4,
    "family_origin_bridge": 4,
    "food_preference_bridge": 4,
    "food_recipe_recommendation_bridge": 5,
    "generic_behavior_inference_bridge": 3,
    "gaming_medium_bridge": 4,
    "hobby_interest_bridge": 4,
    "instrument_play_bridge": 4,
    "travel_country_inventory_bridge": 5,
    "negative_experience_support_bridge": 4,
    "outdoor_nature_memory_bridge": 3,
    "outdoor_preference_bridge": 3,
    "ordinal_answer_bridge": 3,
    "organization_summary_bridge": 4,
    "pet_count_bridge": 4,
    "person_summary_bridge": 4,
    "possession_gift_object_bridge": 4,
    "personality_authenticity_bridge": 4,
    "personality_drive_bridge": 4,
    "personality_thoughtfulness_bridge": 4,
    "personality_trait_bridge": 4,
    "post_event_emotion_bridge": 3,
    "post_event_activity_timing_bridge": 5,
    "post_athletic_career_bridge": 4,
    "military_service_willingness_bridge": 4,
    "music_artist_answer_bridge": 4,
    "music_artist_band_bridge": 4,
    "national_park_inference_bridge": 5,
    "project_summary_bridge": 4,
    "relocation_destination_bridge": 4,
    "relocation_origin_bridge": 4,
    "relocation_willingness_inference_bridge": 4,
    "religious_inference_bridge": 4,
    "running_reason_bridge": 3,
    "running_reason_question_bridge": 4,
    "lgbtq_pride_event_bridge": 4,
    "lgbtq_school_event_bridge": 4,
    "lgbtq_support_group_event_bridge": 4,
    "pottery_type_bridge": 5,
    "public_office_service_bridge": 4,
    "quantity_enumeration_bridge": 2,
    "patriotic_service_inference_bridge": 4,
    "symbol_importance_bridge": 4,
    "temporal_event_detail_bridge": 4,
    "transgender_conference_event_bridge": 4,
    "transgender_poetry_event_bridge": 4,
    "transgender_youth_center_event_bridge": 4,
    "tournament_count_bridge": 4,
    "video_transcript_evidence_bridge": 6,
    "visual_text_evidence_bridge": 6,
    "volunteer_career_inference_bridge": 4,
    "wellness_activity_effect_bridge": 5,
    "decomposition_absence_contrast": 3,
    "decomposition_activity_participation": 4,
    "decomposition_ally_support_evidence": 4,
    "decomposition_artifact_evidence": 5,
    "decomposition_commonality": 3,
    "decomposition_community_membership_evidence": 3,
    "decomposition_conversation_counterparty": 4,
    "decomposition_conversation_recency": 4,
    "decomposition_conversation_topic": 4,
    "decomposition_activity_duration": 4,
    "support_career_motivation_bridge": 4,
    "support_network_bridge": 4,
    "support_origin_bridge": 4,
    "support_role_fit_bridge": 4,
    "decomposition_counterfactual_evidence": 3,
    "decomposition_knowledge_update_current": 2,
    "decomposition_knowledge_update_previous": 2,
    "decomposition_event_sequence": 4,
    "decomposition_inference_support": 2,
    "decomposition_inventory_list": 4,
    "decomposition_support_role_fit": 4,
    "decomposition_temporal_answer": 3,
    "decomposition_lgbtq_pride_event": 4,
    "decomposition_lgbtq_school_speech_event": 4,
    "decomposition_lgbtq_support_group_event": 4,
    "decomposition_frequency_recurrence": 3,
    "decomposition_recommendation_source": 4,
    "decomposition_relocation_context": 3,
    "decomposition_relocation_destination": 3,
    "decomposition_source_evidence": 4,
    "source_evidence_bridge": 4,
    "speaker_turn_bridge": 1,
    "screenplay_count_bridge": 4,
    "shelter_comfort_reason_bridge": 4,
    "state_residence_inference_bridge": 4,
    "stale_state_temporal_bridge": 3,
    "study_time_management_bridge": 4,
    "yoga_delay_gaming_bridge": 4,
}

QUERY_REASON_PRIORITY_MIN_DISTINCTIVE_HITS = {
    "adoption_current_goal_bridge": 2,
    "adoption_current_milestone_bridge": 4,
    "activity_aggregation_bridge": 3,
    "activity_visual_selfcare_bridge": 3,
    "age_birthday_bridge": 2,
    "audio_transcript_evidence_bridge": 3,
    "artifact_inventory_bridge": 2,
    "birthplace_origin_bridge": 2,
    "animal_affinity_pet_store_bridge": 4,
    "animal_care_instruction_bridge": 4,
    "animal_career_inference_bridge": 4,
    "animal_diet_evidence_bridge": 4,
    "animal_habitat_setup_bridge": 4,
    "book_reading_list_bridge": 4,
    "book_suggestion_bridge": 5,
    "children_preference_bridge": 3,
    "beach_count_activity_bridge": 4,
    "business_commonality_bridge": 2,
    "business_networking_event_bridge": 4,
    "business_opening_timeline_bridge": 4,
    "business_promotion_event_bridge": 4,
    "business_start_reason_bridge": 4,
    "business_store_promotion_event_bridge": 4,
    "store_promotion_inventory_bridge": 4,
    "camping_detail_bridge": 4,
    "career_intent_bridge": 4,
    "charity_brand_sponsorship_bridge": 4,
    "children_count_event_bridge": 3,
    "attribute_calm_resourcefulness_bridge": 3,
    "attribute_family_support_bridge": 3,
    "attribute_rescue_purpose_bridge": 3,
    "attribute_service_helpfulness_bridge": 3,
    "attribute_trait_inventory_bridge": 3,
    "ally_support_bridge": 4,
    "allergy_condition_inference_bridge": 4,
    "allergy_inventory_bridge": 4,
    "career_path_bridge": 4,
    "commonality_interest_bridge": 3,
    "community_membership_bridge": 3,
    "community_membership_support_bridge": 3,
    "decomposition_ally_support_evidence": 5,
    "decomposition_community_membership_evidence": 3,
    "current_occupation_bridge": 2,
    "current_residence_bridge": 2,
    "current_recommendation_bridge": 3,
    "current_state_temporal_bridge": 3,
    "stale_state_temporal_bridge": 3,
    "decomposition_absence_contrast": 2,
    "decomposition_activity_participation": 3,
    "decomposition_artifact_evidence": 3,
    "decomposition_inventory_list": 3,
    "decomposition_commonality": 3,
    "decomposition_conversation_counterparty": 4,
    "decomposition_conversation_recency": 4,
    "decomposition_conversation_topic": 4,
    "decomposition_activity_duration": 3,
    "decomposition_counterfactual_evidence": 3,
    "decomposition_event_sequence": 3,
    "decomposition_emotion_cause": 3,
    "decomposition_inference_support": 3,
    "decomposition_knowledge_update_current": 3,
    "decomposition_knowledge_update_previous": 3,
    "decomposition_lgbtq_pride_event": 3,
    "decomposition_lgbtq_school_speech_event": 3,
    "decomposition_lgbtq_support_group_event": 3,
    "decomposition_frequency_recurrence": 3,
    "decomposition_recommendation_source": 5,
    "decomposition_relocation_context": 4,
    "decomposition_relocation_destination": 4,
    "decomposition_source_evidence": 3,
    "decomposition_temporal_answer": 3,
    "deadline_commitment_bridge": 2,
    "decomposition_evidence_reason": 3,
    "decomposition_gotcha_failure": 3,
    "decomposition_state_transition": 3,
    "degree_policy_inference_bridge": 4,
    "endorsement_gear_brand_bridge": 4,
    "education_career_field_bridge": 4,
    "entity_relation_inventory_bridge": 2,
    "event_summary_bridge": 2,
    "exercise_activity_inventory_bridge": 2,
    "followup_task_bridge": 2,
    "gotcha_failure_bridge": 3,
    "state_transition_bridge": 3,
    "family_origin_bridge": 4,
    "food_preference_bridge": 4,
    "food_recipe_recommendation_bridge": 2,
    "generic_behavior_inference_bridge": 3,
    "gaming_medium_bridge": 4,
    "hobby_interest_bridge": 4,
    "hiking_trail_count_bridge": 4,
    "instrument_play_bridge": 4,
    "letter_count_bridge": 4,
    "military_service_willingness_bridge": 3,
    "music_artist_answer_bridge": 4,
    "music_artist_band_bridge": 3,
    "national_park_inference_bridge": 5,
    "outdoor_nature_memory_bridge": 4,
    "outdoor_preference_bridge": 4,
    "ordinal_answer_bridge": 3,
    "organization_summary_bridge": 2,
    "patriotic_service_inference_bridge": 3,
    "pet_count_bridge": 4,
    "pet_inventory_bridge": 4,
    "person_summary_bridge": 2,
    "possession_gift_object_bridge": 4,
    "personality_authenticity_bridge": 4,
    "personality_drive_bridge": 4,
    "personality_thoughtfulness_bridge": 3,
    "personality_trait_bridge": 4,
    "post_event_emotion_bridge": 3,
    "post_event_activity_timing_bridge": 4,
    "post_athletic_career_bridge": 3,
    "public_office_service_bridge": 3,
    "project_summary_bridge": 2,
    "quantity_enumeration_bridge": 3,
    "religious_inference_bridge": 3,
    "running_reason_bridge": 3,
    "running_reason_question_bridge": 3,
    "relocation_willingness_inference_bridge": 3,
    "support_career_motivation_bridge": 4,
    "support_network_bridge": 3,
    "support_origin_bridge": 4,
    "support_role_fit_bridge": 4,
    "source_evidence_bridge": 2,
    "screenplay_count_bridge": 4,
    "shelter_comfort_reason_bridge": 4,
    "state_residence_inference_bridge": 4,
    "study_time_management_bridge": 3,
    "temporal_event_detail_bridge": 4,
    "transgender_youth_center_event_bridge": 4,
    "tournament_count_bridge": 4,
    "video_transcript_evidence_bridge": 3,
    "visual_text_evidence_bridge": 3,
    "volunteer_career_inference_bridge": 3,
    "wellness_activity_effect_bridge": 2,
    "yoga_delay_gaming_bridge": 4,
}

CONTEXT_ITEM_REASON_PRIORITY = {
    **QUERY_REASON_PRIORITY,
    "audio_transcript_evidence_bridge": 4,
    "artifact_inventory_bridge": 4,
    "conversation_transcript_evidence_bridge": 4,
    "personality_drive_bridge": 4,
    "personality_authenticity_bridge": 3,
    "personality_thoughtfulness_bridge": 3,
    "personality_trait_bridge": 2,
    "person_summary_bridge": 3,
    "project_summary_bridge": 3,
    "source_evidence_bridge": 4,
    "speaker_turn_bridge": 4,
    "video_transcript_evidence_bridge": 4,
    "visual_text_evidence_bridge": 4,
    "wellness_activity_effect_bridge": 4,
}

ACTIVITY_OBSERVATION_SOURCE_REASONS = frozenset(
    {
        "activity_aggregation_bridge",
        "activity_visual_selfcare_bridge",
        "decomposition_activity_participation",
        "family_activity_bridge",
        "family_hike_detail_bridge",
        "family_hike_activity_bridge",
        "food_recipe_recommendation_bridge",
        "family_museum_activity_bridge",
        "family_painting_activity_bridge",
        "family_swimming_activity_bridge",
        "painting_inventory_bridge",
    }
)
DERIVED_SUMMARY_SOURCE_REASONS = frozenset(
    {
        *ACTIVITY_OBSERVATION_SOURCE_REASONS,
        "adoption_current_goal_bridge",
        "adoption_current_milestone_bridge",
        "beach_count_activity_bridge",
        "animal_affinity_pet_store_bridge",
        "animal_care_instruction_bridge",
        "animal_career_inference_bridge",
        "animal_diet_evidence_bridge",
        "animal_habitat_setup_bridge",
        "attribute_calm_resourcefulness_bridge",
        "attribute_description_bridge",
        "attribute_family_support_bridge",
        "attribute_rescue_purpose_bridge",
        "attribute_service_helpfulness_bridge",
        "attribute_trait_inventory_bridge",
        "ally_support_bridge",
        "allergy_condition_inference_bridge",
        "allergy_inventory_bridge",
        "audio_transcript_evidence_bridge",
        "artifact_inventory_bridge",
        "birdwatching_city_schedule_bridge",
        "book_reading_list_bridge",
        "food_recipe_recommendation_bridge",
        "business_commonality_bridge",
        "business_networking_event_bridge",
        "business_opening_timeline_bridge",
        "business_promotion_event_bridge",
        "business_start_reason_bridge",
        "business_store_promotion_event_bridge",
        "store_promotion_inventory_bridge",
        "camping_detail_bridge",
        "charity_brand_sponsorship_bridge",
        "charity_tournament_count_bridge",
        "children_count_event_bridge",
        "decomposition_ally_support_evidence",
        "community_membership_bridge",
        "community_membership_support_bridge",
        "decomposition_community_membership_evidence",
        "cause_education_infrastructure_inventory_bridge",
        "cause_veterans_inventory_bridge",
        "decomposition_inventory_list",
        "degree_policy_inference_bridge",
        "entity_relation_inventory_bridge",
        "event_summary_bridge",
        "exercise_activity_inventory_bridge",
        "endorsement_gear_brand_bridge",
        "event_participation_bridge",
        "event_participation_help_bridge",
        "family_origin_bridge",
        "friend_place_inventory_bridge",
        "friend_place_shelter_inventory_bridge",
        "friend_place_gym_inventory_bridge",
        "friend_place_church_inventory_bridge",
        "food_preference_bridge",
        "family_hike_activity_bridge",
        "gaming_medium_bridge",
        "hike_count_activity_bridge",
        "hiking_trail_count_bridge",
        "hobby_interest_bridge",
        "instrument_play_bridge",
        "item_purchase_bridge",
        "letter_count_bridge",
        "lgbtq_community_participation_bridge",
        "lgbtq_pride_event_bridge",
        "lgbtq_school_event_bridge",
        "lgbtq_support_group_event_bridge",
        "meteor_shower_feeling_bridge",
        "military_service_willingness_bridge",
        "national_park_inference_bridge",
        "patriotic_service_inference_bridge",
        "pet_count_bridge",
        "pet_inventory_bridge",
        "organization_summary_bridge",
        "possession_gift_object_bridge",
        "personality_authenticity_bridge",
        "personality_drive_bridge",
        "personality_thoughtfulness_bridge",
        "personality_trait_bridge",
        "person_summary_bridge",
        "post_event_emotion_bridge",
        "post_event_activity_timing_bridge",
        "post_athletic_career_bridge",
        "pottery_type_bridge",
        "project_summary_bridge",
        "public_office_service_bridge",
        "relocation_willingness_inference_bridge",
        "religious_inference_bridge",
        "running_reason_bridge",
        "running_reason_question_bridge",
        "screenplay_count_bridge",
        "shelter_comfort_reason_bridge",
        "state_residence_inference_bridge",
        "study_time_management_bridge",
        "support_network_bridge",
        "support_role_fit_bridge",
        "symbol_importance_bridge",
        "temporal_event_detail_bridge",
        "travel_country_inventory_bridge",
        "transgender_conference_event_bridge",
        "transgender_poetry_event_bridge",
        "transgender_youth_center_event_bridge",
        "tournament_count_bridge",
        "video_transcript_evidence_bridge",
        "visual_text_evidence_bridge",
        "volunteer_career_inference_bridge",
        "wellness_activity_effect_bridge",
        "yoga_delay_gaming_bridge",
    }
)
DERIVED_SUMMARY_SOURCE_MIN_DISTINCTIVE_HITS = {
    "adoption_current_goal_bridge": 3,
    "adoption_current_milestone_bridge": 4,
    "event_participation_bridge": 6,
    "event_participation_help_bridge": 6,
    "beach_count_activity_bridge": 4,
    "food_preference_bridge": 4,
    "animal_affinity_pet_store_bridge": 4,
    "animal_care_instruction_bridge": 4,
    "animal_career_inference_bridge": 4,
    "animal_diet_evidence_bridge": 4,
    "animal_habitat_setup_bridge": 4,
    "attribute_calm_resourcefulness_bridge": 3,
    "attribute_description_bridge": 4,
    "attribute_family_support_bridge": 3,
    "attribute_rescue_purpose_bridge": 3,
    "attribute_service_helpfulness_bridge": 3,
    "attribute_trait_inventory_bridge": 3,
    "ally_support_bridge": 4,
    "allergy_condition_inference_bridge": 4,
    "allergy_inventory_bridge": 4,
    "audio_transcript_evidence_bridge": 3,
    "artifact_inventory_bridge": 3,
    "birdwatching_city_schedule_bridge": 4,
    "book_reading_list_bridge": 4,
    "business_commonality_bridge": 2,
    "business_networking_event_bridge": 4,
    "business_opening_timeline_bridge": 4,
    "business_promotion_event_bridge": 4,
    "business_start_reason_bridge": 4,
    "business_store_promotion_event_bridge": 4,
    "store_promotion_inventory_bridge": 4,
    "camping_detail_bridge": 4,
    "charity_brand_sponsorship_bridge": 4,
    "charity_tournament_count_bridge": 4,
    "children_count_event_bridge": 3,
    "decomposition_ally_support_evidence": 5,
    "community_membership_bridge": 3,
    "community_membership_support_bridge": 3,
    "decomposition_community_membership_evidence": 3,
    "cause_education_infrastructure_inventory_bridge": 4,
    "cause_veterans_inventory_bridge": 4,
    "decomposition_inventory_list": 4,
    "degree_policy_inference_bridge": 4,
    "entity_relation_inventory_bridge": 3,
    "event_summary_bridge": 3,
    "exercise_activity_inventory_bridge": 2,
    "endorsement_gear_brand_bridge": 4,
    "friend_place_inventory_bridge": 4,
    "friend_place_shelter_inventory_bridge": 4,
    "friend_place_gym_inventory_bridge": 4,
    "friend_place_church_inventory_bridge": 4,
    "family_activity_bridge": 5,
    "family_hike_detail_bridge": 5,
    "family_hike_activity_bridge": 5,
    "family_museum_activity_bridge": 5,
    "family_painting_activity_bridge": 5,
    "family_swimming_activity_bridge": 5,
    "gaming_medium_bridge": 4,
    "hike_count_activity_bridge": 4,
    "hiking_trail_count_bridge": 4,
    "hobby_interest_bridge": 4,
    "instrument_play_bridge": 4,
    "item_purchase_bridge": 5,
    "letter_count_bridge": 4,
    "lgbtq_community_participation_bridge": 5,
    "lgbtq_pride_event_bridge": 5,
    "lgbtq_school_event_bridge": 5,
    "lgbtq_support_group_event_bridge": 5,
    "meteor_shower_feeling_bridge": 3,
    "military_service_willingness_bridge": 3,
    "national_park_inference_bridge": 4,
    "patriotic_service_inference_bridge": 3,
    "pet_count_bridge": 4,
    "pet_inventory_bridge": 4,
    "possession_gift_object_bridge": 4,
    "personality_authenticity_bridge": 4,
    "personality_drive_bridge": 4,
    "personality_thoughtfulness_bridge": 4,
    "personality_trait_bridge": 5,
    "organization_summary_bridge": 3,
    "person_summary_bridge": 3,
    "post_event_emotion_bridge": 3,
    "post_event_activity_timing_bridge": 4,
    "post_athletic_career_bridge": 3,
    "pottery_type_bridge": 4,
    "project_summary_bridge": 3,
    "public_office_service_bridge": 3,
    "religious_inference_bridge": 3,
    "running_reason_bridge": 3,
    "running_reason_question_bridge": 3,
    "screenplay_count_bridge": 4,
    "shelter_comfort_reason_bridge": 4,
    "relocation_willingness_inference_bridge": 3,
    "state_residence_inference_bridge": 4,
    "study_time_management_bridge": 3,
    "support_network_bridge": 3,
    "support_role_fit_bridge": 4,
    "symbol_importance_bridge": 3,
    "temporal_event_detail_bridge": 4,
    "travel_country_inventory_bridge": 4,
    "transgender_conference_event_bridge": 4,
    "transgender_poetry_event_bridge": 4,
    "transgender_youth_center_event_bridge": 4,
    "tournament_count_bridge": 4,
    "video_transcript_evidence_bridge": 3,
    "visual_text_evidence_bridge": 3,
    "volunteer_career_inference_bridge": 3,
    "yoga_delay_gaming_bridge": 4,
}
ACTIVITY_OWNER_REASONS = frozenset(
    {
        *ACTIVITY_OBSERVATION_SOURCE_REASONS,
        "friend_place_inventory_bridge",
        "friend_place_shelter_inventory_bridge",
        "friend_place_gym_inventory_bridge",
        "friend_place_church_inventory_bridge",
    }
)
PRECISE_TURN_SOURCE_SIBLING_REASONS = frozenset(
    {
        *ACTIVITY_OBSERVATION_SOURCE_REASONS,
        "adoption_current_goal_bridge",
        "adoption_current_milestone_bridge",
        "animal_care_instruction_bridge",
        "allergy_condition_inference_bridge",
        "attribute_calm_resourcefulness_bridge",
        "attribute_family_support_bridge",
        "attribute_rescue_purpose_bridge",
        "attribute_service_helpfulness_bridge",
        "attribute_trait_inventory_bridge",
        "beach_count_activity_bridge",
        "birdwatching_city_schedule_bridge",
        "book_reading_list_bridge",
        "book_suggestion_bridge",
        "business_commonality_bridge",
        "business_networking_event_bridge",
        "business_opening_timeline_bridge",
        "business_promotion_event_bridge",
        "business_store_promotion_event_bridge",
        "store_promotion_inventory_bridge",
        "children_count_event_bridge",
        "children_count_sibling_bridge",
        "cause_education_infrastructure_inventory_bridge",
        "cause_veterans_inventory_bridge",
        "decomposition_conversation_recency",
        "decomposition_lgbtq_pride_event",
        "decomposition_lgbtq_school_speech_event",
        "decomposition_lgbtq_support_group_event",
        "decomposition_inventory_list",
        "decomposition_recommendation_source",
        "degree_policy_inference_bridge",
        "exercise_activity_inventory_bridge",
        "event_participation_bridge",
        "event_participation_help_bridge",
        "friend_place_inventory_bridge",
        "friend_place_shelter_inventory_bridge",
        "friend_place_gym_inventory_bridge",
        "friend_place_church_inventory_bridge",
        "hike_count_activity_bridge",
        "hiking_trail_count_bridge",
        "travel_country_inventory_bridge",
        "lgbtq_pride_event_bridge",
        "lgbtq_school_event_bridge",
        "lgbtq_support_group_event_bridge",
        "meteor_shower_feeling_bridge",
        "national_park_inference_bridge",
        "patriotic_service_inference_bridge",
        "painting_inventory_bridge",
        "post_athletic_career_bridge",
        "post_event_activity_timing_bridge",
        "recommendation_source_bridge",
        "running_reason_bridge",
        "running_reason_question_bridge",
        "shoe_usage_bridge",
        "support_career_motivation_bridge",
        "support_network_bridge",
        "support_origin_bridge",
        "support_role_fit_bridge",
        "study_time_management_bridge",
        "symbol_importance_bridge",
        "transgender_conference_event_bridge",
        "transgender_poetry_event_bridge",
        "transgender_youth_center_event_bridge",
        "volunteer_career_inference_bridge",
    }
)
